version: '3.8'

services:
  mysql-user:
    image: mysql:8.0
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ticket_user
    ports:
      - "3306:3306"
    volumes:
      - mysql-user-data:/var/lib/mysql

volumes:
  mysql-user-data: